# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/VivadoProjects/demo_cusum_ewma_zscore_multi/demo_cusum_ewma_zscore_multi/demo_cusum_ewma_zscore_multi.srcs/sources_1/ip/fifo16x64/fifo16x64.xci
# IP: The module: 'fifo16x64' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/VivadoProjects/demo_cusum_ewma_zscore_multi/demo_cusum_ewma_zscore_multi/int_cusum_multi_stream.gen/sources_1/ip/fifo16x64/fifo16x64_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo16x64'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: E:/VivadoProjects/demo_cusum_ewma_zscore_multi/demo_cusum_ewma_zscore_multi/demo_cusum_ewma_zscore_multi.srcs/sources_1/ip/fifo16x64/fifo16x64.xci
# IP: The module: 'fifo16x64' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/VivadoProjects/demo_cusum_ewma_zscore_multi/demo_cusum_ewma_zscore_multi/int_cusum_multi_stream.gen/sources_1/ip/fifo16x64/fifo16x64_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo16x64'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
