# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/VivadoProjects/demo_cusum_ewma_zscore_multi/demo_cusum_ewma_zscore_multi/demo_cusum_ewma_zscore_multi.srcs/sources_1/ip/fifo32x16_buffering/fifo32x16_buffering.xci
# IP: The module: 'fifo32x16_buffering' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/VivadoProjects/demo_cusum_ewma_zscore_multi/demo_cusum_ewma_zscore_multi/lic_proj3.gen/sources_1/ip/fifo32x16_buffering/fifo32x16_buffering_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo32x16_buffering'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: E:/VivadoProjects/demo_cusum_ewma_zscore_multi/demo_cusum_ewma_zscore_multi/demo_cusum_ewma_zscore_multi.srcs/sources_1/ip/fifo32x16_buffering/fifo32x16_buffering.xci
# IP: The module: 'fifo32x16_buffering' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/VivadoProjects/demo_cusum_ewma_zscore_multi/demo_cusum_ewma_zscore_multi/lic_proj3.gen/sources_1/ip/fifo32x16_buffering/fifo32x16_buffering_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo32x16_buffering'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
